public enum TokenType {

    LEFT_PAREN,RIGHT_PAREN,LEFT_BRACE,RIGTH_BRACE,
    COMMA,MINUS,PLUS,MULT,DIV,SEMICOLON,WHITESPACE,


    EQUAL,EQUAL_EQUAL,GREATER,
    LESS,NOT_EQUAL,


    IDENTIFIER,STRING,NUMBER,


    AND,ELSE,FALSE,IF,OR,
    PRINT,VAR, WHILE,DO,

    //undefined
    UNDEFINED
}
